plugin: aws_ec2
regions:
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
filters:
  # All instances with their `technology` tag set to the service that is being installed
  tag:technology: technology_label_value
  #TODO: get only ec2 instances that are in running state
  #instance-state-code: 16
strict: False
keyed_groups:
  - key: tags.technology
    prefix: ""
    separator: ""
  - key: placement.region + "_" + tags.technology
    prefix: ""
    separator: ""
compose:
  # Use the public IP address to connect to the host
  # (note: this does not modify inventory_hostname, which is set via I(hostnames))
  ansible_host: ip_address

#boto_profile: aws_profile
aws_access_key_id: aws_accss_key_id
aws_secret_key: aws_key