plugin: gcp_compute
zones: # populate inventory with instances in these regions
  - us-east1-b
  - us-east1-c
  - us-east1-d
  - us-central1-a
  - us-central1-b
  - us-central1-c
  - us-central1-f
projects:
  - gcp_project_id
filters:
  - labels.technology = technology_label_value
  - status = RUNNING
service_account_file: service_account.gcp.json
auth_kind: serviceaccount
scopes:
 - 'https://www.googleapis.com/auth/cloud-platform'
 - 'https://www.googleapis.com/auth/compute.readonly'
keyed_groups:
  # Create groups from GCE labels
  - key: labels.technology
    prefix: ""
    separator: ""
  - key: networkInterfaces[0].subnetwork.region + "_" + labels.technology
    prefix: ""
    separator: ""    
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
