---

- name: Download Tomcat and set sym links
  become: yes
  shell: |
    groupadd tomcat 
    useradd -s /bin/nologin -g tomcat -d /opt/tomcat tomcat
    mkdir -p /opt/tomcat && chmod -R 755 /opt/tomcat && cd /opt/tomcat
    wget --no-check-certificate https://mirrors.sonic.net/apache/tomcat/tomcat-8/v8.5.88/bin/apache-tomcat-8.5.88.tar.gz
    tar -xzf apache-tomcat-8.5.88.tar.gz -C /opt/tomcat --strip-components=1
    cd /opt/tomcat
    chgrp -R tomcat conf
    chmod g+r conf/*
    chown -R tomcat logs/ temp/ webapps/ work/
    chgrp -R tomcat bin
    chgrp -R tomcat lib
    chmod g+rwx bin
    chmod g+r bin/*
    ln -s /opt/tomcat/bin/startup.sh /usr/sbin/tomcatup
    ln -s /opt/tomcat/bin/shutdown.sh /usr/sbin/tomcatdown
    chmod +x /opt/tomcat/bin/startup.sh /opt/tomcat/bin/shutdown.sh
  register: execute_shell
  until: execute_shell is not failed
  retries: 20
  delay: 10

- name: Configure tomcat role and user
  vars:
    tomcat_admin_username : admin
    tomcat_admin_pw: s3cret
  become: yes
  template:
    src: templates/tomcat-users.xml.j2
    dest: /opt/tomcat/conf/tomcat-users.xml
  register: user_config_success
  until: user_config_success is not failed
  retries: 5
  delay: 5



- name: Enable access to Manager page on Tomcat
  become: yes
  template:
    src: templates/tomcat-meta-context.xml
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml
  register: context_file_copy
  until: context_file_copy is not failed
  retries: 5
  delay: 5
  
- name: Start Tomcat
  become: yes
  shell: |
    tomcatup
  register: tomcat_startup
  until: tomcat_startup is not failed
  retries: 20
  delay: 10
